### ISSUE TITLE
Is this obsoleted by the CI build?

### ISSUE THREAD

**Issue by GitMensch** [zhanghua000/vscode-loc#1]
see https://open-vsx.org/extension/MS-CEINTL/vscode-language-pack-zh-hans, originating from https://github.com/open-vsx/publish-extensions/issues/117

**Comment by zhanghua000** [comment]
At first, Microsoft don't upload a official version of this language pack, I fork from them and create this unofficial one. Nowadays, Microsoft has the official version in the address, so I think it is not necessary to continue porting, I want to transform this project to a unofficial version but I am a student, I don't have too much time working on it. I am speaking Chinese so I use travis  to build Chinese Language Pack. You can see details in the `.travis.yml` file.

**Comment by GitMensch** [comment]
Microsoft said they don't want to upload it themselves - but the CI build now does this automatically (from the official MS repo), always up to date. So I _guess_ that your good work, which was necessary before the CI build, can be considered "done".

What do you think?

**Comment by zhanghua000** [comment]
Yes, I think so.
